openapi: 3.0.1
info:
  title: Recommendation API
  version: 1.0.0

paths:
  /recommend:
    post:
      summary: Get recommendations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
              required:
                - data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  recommendations:
                    type: array
                    items:
                      type: string
                      example: "recommendation1"
        '400':
          description: Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Validation error message"
